/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "orc_proto.pb-c.h"
void   integer_statistics__init
                     (IntegerStatistics         *message)
{
  static IntegerStatistics init_value = INTEGER_STATISTICS__INIT;
  *message = init_value;
}
size_t integer_statistics__get_packed_size
                     (const IntegerStatistics *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &integer_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t integer_statistics__pack
                     (const IntegerStatistics *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &integer_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t integer_statistics__pack_to_buffer
                     (const IntegerStatistics *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &integer_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IntegerStatistics *
       integer_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IntegerStatistics *)
     protobuf_c_message_unpack (&integer_statistics__descriptor,
                                allocator, len, data);
}
void   integer_statistics__free_unpacked
                     (IntegerStatistics *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &integer_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   double_statistics__init
                     (DoubleStatistics         *message)
{
  static DoubleStatistics init_value = DOUBLE_STATISTICS__INIT;
  *message = init_value;
}
size_t double_statistics__get_packed_size
                     (const DoubleStatistics *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &double_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t double_statistics__pack
                     (const DoubleStatistics *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &double_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t double_statistics__pack_to_buffer
                     (const DoubleStatistics *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &double_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DoubleStatistics *
       double_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DoubleStatistics *)
     protobuf_c_message_unpack (&double_statistics__descriptor,
                                allocator, len, data);
}
void   double_statistics__free_unpacked
                     (DoubleStatistics *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &double_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   string_statistics__init
                     (StringStatistics         *message)
{
  static StringStatistics init_value = STRING_STATISTICS__INIT;
  *message = init_value;
}
size_t string_statistics__get_packed_size
                     (const StringStatistics *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &string_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t string_statistics__pack
                     (const StringStatistics *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &string_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t string_statistics__pack_to_buffer
                     (const StringStatistics *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &string_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StringStatistics *
       string_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StringStatistics *)
     protobuf_c_message_unpack (&string_statistics__descriptor,
                                allocator, len, data);
}
void   string_statistics__free_unpacked
                     (StringStatistics *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &string_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bucket_statistics__init
                     (BucketStatistics         *message)
{
  static BucketStatistics init_value = BUCKET_STATISTICS__INIT;
  *message = init_value;
}
size_t bucket_statistics__get_packed_size
                     (const BucketStatistics *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &bucket_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bucket_statistics__pack
                     (const BucketStatistics *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &bucket_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bucket_statistics__pack_to_buffer
                     (const BucketStatistics *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &bucket_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BucketStatistics *
       bucket_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BucketStatistics *)
     protobuf_c_message_unpack (&bucket_statistics__descriptor,
                                allocator, len, data);
}
void   bucket_statistics__free_unpacked
                     (BucketStatistics *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &bucket_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   decimal_statistics__init
                     (DecimalStatistics         *message)
{
  static DecimalStatistics init_value = DECIMAL_STATISTICS__INIT;
  *message = init_value;
}
size_t decimal_statistics__get_packed_size
                     (const DecimalStatistics *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &decimal_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t decimal_statistics__pack
                     (const DecimalStatistics *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &decimal_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t decimal_statistics__pack_to_buffer
                     (const DecimalStatistics *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &decimal_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DecimalStatistics *
       decimal_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DecimalStatistics *)
     protobuf_c_message_unpack (&decimal_statistics__descriptor,
                                allocator, len, data);
}
void   decimal_statistics__free_unpacked
                     (DecimalStatistics *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &decimal_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   column_statistics__init
                     (ColumnStatistics         *message)
{
  static ColumnStatistics init_value = COLUMN_STATISTICS__INIT;
  *message = init_value;
}
size_t column_statistics__get_packed_size
                     (const ColumnStatistics *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &column_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t column_statistics__pack
                     (const ColumnStatistics *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &column_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t column_statistics__pack_to_buffer
                     (const ColumnStatistics *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &column_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ColumnStatistics *
       column_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ColumnStatistics *)
     protobuf_c_message_unpack (&column_statistics__descriptor,
                                allocator, len, data);
}
void   column_statistics__free_unpacked
                     (ColumnStatistics *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &column_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   row_index_entry__init
                     (RowIndexEntry         *message)
{
  static RowIndexEntry init_value = ROW_INDEX_ENTRY__INIT;
  *message = init_value;
}
size_t row_index_entry__get_packed_size
                     (const RowIndexEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &row_index_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t row_index_entry__pack
                     (const RowIndexEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &row_index_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t row_index_entry__pack_to_buffer
                     (const RowIndexEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &row_index_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RowIndexEntry *
       row_index_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RowIndexEntry *)
     protobuf_c_message_unpack (&row_index_entry__descriptor,
                                allocator, len, data);
}
void   row_index_entry__free_unpacked
                     (RowIndexEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &row_index_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   row_index__init
                     (RowIndex         *message)
{
  static RowIndex init_value = ROW_INDEX__INIT;
  *message = init_value;
}
size_t row_index__get_packed_size
                     (const RowIndex *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &row_index__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t row_index__pack
                     (const RowIndex *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &row_index__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t row_index__pack_to_buffer
                     (const RowIndex *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &row_index__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RowIndex *
       row_index__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RowIndex *)
     protobuf_c_message_unpack (&row_index__descriptor,
                                allocator, len, data);
}
void   row_index__free_unpacked
                     (RowIndex *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &row_index__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stream__init
                     (Stream         *message)
{
  static Stream init_value = STREAM__INIT;
  *message = init_value;
}
size_t stream__get_packed_size
                     (const Stream *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &stream__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stream__pack
                     (const Stream *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &stream__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stream__pack_to_buffer
                     (const Stream *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &stream__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Stream *
       stream__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Stream *)
     protobuf_c_message_unpack (&stream__descriptor,
                                allocator, len, data);
}
void   stream__free_unpacked
                     (Stream *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &stream__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   column_encoding__init
                     (ColumnEncoding         *message)
{
  static ColumnEncoding init_value = COLUMN_ENCODING__INIT;
  *message = init_value;
}
size_t column_encoding__get_packed_size
                     (const ColumnEncoding *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &column_encoding__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t column_encoding__pack
                     (const ColumnEncoding *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &column_encoding__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t column_encoding__pack_to_buffer
                     (const ColumnEncoding *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &column_encoding__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ColumnEncoding *
       column_encoding__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ColumnEncoding *)
     protobuf_c_message_unpack (&column_encoding__descriptor,
                                allocator, len, data);
}
void   column_encoding__free_unpacked
                     (ColumnEncoding *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &column_encoding__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stripe_footer__init
                     (StripeFooter         *message)
{
  static StripeFooter init_value = STRIPE_FOOTER__INIT;
  *message = init_value;
}
size_t stripe_footer__get_packed_size
                     (const StripeFooter *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &stripe_footer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stripe_footer__pack
                     (const StripeFooter *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &stripe_footer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stripe_footer__pack_to_buffer
                     (const StripeFooter *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &stripe_footer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StripeFooter *
       stripe_footer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StripeFooter *)
     protobuf_c_message_unpack (&stripe_footer__descriptor,
                                allocator, len, data);
}
void   stripe_footer__free_unpacked
                     (StripeFooter *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &stripe_footer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   type__init
                     (Type         *message)
{
  static Type init_value = TYPE__INIT;
  *message = init_value;
}
size_t type__get_packed_size
                     (const Type *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &type__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t type__pack
                     (const Type *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &type__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t type__pack_to_buffer
                     (const Type *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &type__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Type *
       type__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Type *)
     protobuf_c_message_unpack (&type__descriptor,
                                allocator, len, data);
}
void   type__free_unpacked
                     (Type *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &type__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   stripe_information__init
                     (StripeInformation         *message)
{
  static StripeInformation init_value = STRIPE_INFORMATION__INIT;
  *message = init_value;
}
size_t stripe_information__get_packed_size
                     (const StripeInformation *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &stripe_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t stripe_information__pack
                     (const StripeInformation *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &stripe_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t stripe_information__pack_to_buffer
                     (const StripeInformation *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &stripe_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
StripeInformation *
       stripe_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (StripeInformation *)
     protobuf_c_message_unpack (&stripe_information__descriptor,
                                allocator, len, data);
}
void   stripe_information__free_unpacked
                     (StripeInformation *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &stripe_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   user_metadata_item__init
                     (UserMetadataItem         *message)
{
  static UserMetadataItem init_value = USER_METADATA_ITEM__INIT;
  *message = init_value;
}
size_t user_metadata_item__get_packed_size
                     (const UserMetadataItem *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user_metadata_item__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t user_metadata_item__pack
                     (const UserMetadataItem *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user_metadata_item__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t user_metadata_item__pack_to_buffer
                     (const UserMetadataItem *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user_metadata_item__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UserMetadataItem *
       user_metadata_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UserMetadataItem *)
     protobuf_c_message_unpack (&user_metadata_item__descriptor,
                                allocator, len, data);
}
void   user_metadata_item__free_unpacked
                     (UserMetadataItem *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user_metadata_item__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   footer__init
                     (Footer         *message)
{
  static Footer init_value = FOOTER__INIT;
  *message = init_value;
}
size_t footer__get_packed_size
                     (const Footer *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &footer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t footer__pack
                     (const Footer *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &footer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t footer__pack_to_buffer
                     (const Footer *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &footer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Footer *
       footer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Footer *)
     protobuf_c_message_unpack (&footer__descriptor,
                                allocator, len, data);
}
void   footer__free_unpacked
                     (Footer *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &footer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   post_script__init
                     (PostScript         *message)
{
  static PostScript init_value = POST_SCRIPT__INIT;
  *message = init_value;
}
size_t post_script__get_packed_size
                     (const PostScript *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &post_script__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t post_script__pack
                     (const PostScript *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &post_script__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t post_script__pack_to_buffer
                     (const PostScript *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &post_script__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PostScript *
       post_script__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PostScript *)
     protobuf_c_message_unpack (&post_script__descriptor,
                                allocator, len, data);
}
void   post_script__free_unpacked
                     (PostScript *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &post_script__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor integer_statistics__field_descriptors[3] =
{
  {
    "minimum",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    PROTOBUF_C_OFFSETOF(IntegerStatistics, has_minimum),
    PROTOBUF_C_OFFSETOF(IntegerStatistics, minimum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maximum",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    PROTOBUF_C_OFFSETOF(IntegerStatistics, has_maximum),
    PROTOBUF_C_OFFSETOF(IntegerStatistics, maximum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sum",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_SINT64,
    PROTOBUF_C_OFFSETOF(IntegerStatistics, has_sum),
    PROTOBUF_C_OFFSETOF(IntegerStatistics, sum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned integer_statistics__field_indices_by_name[] = {
  1,   /* field[1] = maximum */
  0,   /* field[0] = minimum */
  2,   /* field[2] = sum */
};
static const ProtobufCIntRange integer_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor integer_statistics__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "IntegerStatistics",
  "IntegerStatistics",
  "IntegerStatistics",
  "",
  sizeof(IntegerStatistics),
  3,
  integer_statistics__field_descriptors,
  integer_statistics__field_indices_by_name,
  1,  integer_statistics__number_ranges,
  (ProtobufCMessageInit) integer_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor double_statistics__field_descriptors[3] =
{
  {
    "minimum",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    PROTOBUF_C_OFFSETOF(DoubleStatistics, has_minimum),
    PROTOBUF_C_OFFSETOF(DoubleStatistics, minimum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maximum",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    PROTOBUF_C_OFFSETOF(DoubleStatistics, has_maximum),
    PROTOBUF_C_OFFSETOF(DoubleStatistics, maximum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sum",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    PROTOBUF_C_OFFSETOF(DoubleStatistics, has_sum),
    PROTOBUF_C_OFFSETOF(DoubleStatistics, sum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned double_statistics__field_indices_by_name[] = {
  1,   /* field[1] = maximum */
  0,   /* field[0] = minimum */
  2,   /* field[2] = sum */
};
static const ProtobufCIntRange double_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor double_statistics__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "DoubleStatistics",
  "DoubleStatistics",
  "DoubleStatistics",
  "",
  sizeof(DoubleStatistics),
  3,
  double_statistics__field_descriptors,
  double_statistics__field_indices_by_name,
  1,  double_statistics__number_ranges,
  (ProtobufCMessageInit) double_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor string_statistics__field_descriptors[2] =
{
  {
    "minimum",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(StringStatistics, minimum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maximum",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(StringStatistics, maximum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned string_statistics__field_indices_by_name[] = {
  1,   /* field[1] = maximum */
  0,   /* field[0] = minimum */
};
static const ProtobufCIntRange string_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor string_statistics__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "StringStatistics",
  "StringStatistics",
  "StringStatistics",
  "",
  sizeof(StringStatistics),
  2,
  string_statistics__field_descriptors,
  string_statistics__field_indices_by_name,
  1,  string_statistics__number_ranges,
  (ProtobufCMessageInit) string_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bucket_statistics__field_descriptors[1] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(BucketStatistics, n_count),
    PROTOBUF_C_OFFSETOF(BucketStatistics, count),
    NULL,
    NULL,
    1,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bucket_statistics__field_indices_by_name[] = {
  0,   /* field[0] = count */
};
static const ProtobufCIntRange bucket_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor bucket_statistics__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "BucketStatistics",
  "BucketStatistics",
  "BucketStatistics",
  "",
  sizeof(BucketStatistics),
  1,
  bucket_statistics__field_descriptors,
  bucket_statistics__field_indices_by_name,
  1,  bucket_statistics__number_ranges,
  (ProtobufCMessageInit) bucket_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor decimal_statistics__field_descriptors[3] =
{
  {
    "minimum",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DecimalStatistics, minimum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maximum",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DecimalStatistics, maximum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sum",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(DecimalStatistics, sum),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned decimal_statistics__field_indices_by_name[] = {
  1,   /* field[1] = maximum */
  0,   /* field[0] = minimum */
  2,   /* field[2] = sum */
};
static const ProtobufCIntRange decimal_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor decimal_statistics__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "DecimalStatistics",
  "DecimalStatistics",
  "DecimalStatistics",
  "",
  sizeof(DecimalStatistics),
  3,
  decimal_statistics__field_descriptors,
  decimal_statistics__field_indices_by_name,
  1,  decimal_statistics__number_ranges,
  (ProtobufCMessageInit) decimal_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor column_statistics__field_descriptors[6] =
{
  {
    "numberOfValues",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(ColumnStatistics, has_numberofvalues),
    PROTOBUF_C_OFFSETOF(ColumnStatistics, numberofvalues),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "intStatistics",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ColumnStatistics, intstatistics),
    &integer_statistics__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "doubleStatistics",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ColumnStatistics, doublestatistics),
    &double_statistics__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stringStatistics",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ColumnStatistics, stringstatistics),
    &string_statistics__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bucketStatistics",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ColumnStatistics, bucketstatistics),
    &bucket_statistics__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "decimalStatistics",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ColumnStatistics, decimalstatistics),
    &decimal_statistics__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned column_statistics__field_indices_by_name[] = {
  4,   /* field[4] = bucketStatistics */
  5,   /* field[5] = decimalStatistics */
  2,   /* field[2] = doubleStatistics */
  1,   /* field[1] = intStatistics */
  0,   /* field[0] = numberOfValues */
  3,   /* field[3] = stringStatistics */
};
static const ProtobufCIntRange column_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor column_statistics__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ColumnStatistics",
  "ColumnStatistics",
  "ColumnStatistics",
  "",
  sizeof(ColumnStatistics),
  6,
  column_statistics__field_descriptors,
  column_statistics__field_indices_by_name,
  1,  column_statistics__number_ranges,
  (ProtobufCMessageInit) column_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor row_index_entry__field_descriptors[2] =
{
  {
    "positions",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(RowIndexEntry, n_positions),
    PROTOBUF_C_OFFSETOF(RowIndexEntry, positions),
    NULL,
    NULL,
    1,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "statistics",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(RowIndexEntry, statistics),
    &column_statistics__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned row_index_entry__field_indices_by_name[] = {
  0,   /* field[0] = positions */
  1,   /* field[1] = statistics */
};
static const ProtobufCIntRange row_index_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor row_index_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RowIndexEntry",
  "RowIndexEntry",
  "RowIndexEntry",
  "",
  sizeof(RowIndexEntry),
  2,
  row_index_entry__field_descriptors,
  row_index_entry__field_indices_by_name,
  1,  row_index_entry__number_ranges,
  (ProtobufCMessageInit) row_index_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor row_index__field_descriptors[1] =
{
  {
    "entry",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(RowIndex, n_entry),
    PROTOBUF_C_OFFSETOF(RowIndex, entry),
    &row_index_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned row_index__field_indices_by_name[] = {
  0,   /* field[0] = entry */
};
static const ProtobufCIntRange row_index__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor row_index__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "RowIndex",
  "RowIndex",
  "RowIndex",
  "",
  sizeof(RowIndex),
  1,
  row_index__field_descriptors,
  row_index__field_indices_by_name,
  1,  row_index__number_ranges,
  (ProtobufCMessageInit) row_index__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue stream__kind__enum_values_by_number[7] =
{
  { "PRESENT", "STREAM__KIND__PRESENT", 0 },
  { "DATA", "STREAM__KIND__DATA", 1 },
  { "LENGTH", "STREAM__KIND__LENGTH", 2 },
  { "DICTIONARY_DATA", "STREAM__KIND__DICTIONARY_DATA", 3 },
  { "DICTIONARY_COUNT", "STREAM__KIND__DICTIONARY_COUNT", 4 },
  { "SECONDARY", "STREAM__KIND__SECONDARY", 5 },
  { "ROW_INDEX", "STREAM__KIND__ROW_INDEX", 6 },
};
static const ProtobufCIntRange stream__kind__value_ranges[] = {
{0, 0},{0, 7}
};
const ProtobufCEnumValueIndex stream__kind__enum_values_by_name[7] =
{
  { "DATA", 1 },
  { "DICTIONARY_COUNT", 4 },
  { "DICTIONARY_DATA", 3 },
  { "LENGTH", 2 },
  { "PRESENT", 0 },
  { "ROW_INDEX", 6 },
  { "SECONDARY", 5 },
};
const ProtobufCEnumDescriptor stream__kind__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "Stream.Kind",
  "Kind",
  "Stream__Kind",
  "",
  7,
  stream__kind__enum_values_by_number,
  7,
  stream__kind__enum_values_by_name,
  1,
  stream__kind__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor stream__field_descriptors[3] =
{
  {
    "kind",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Stream, kind),
    &stream__kind__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "column",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Stream, has_column),
    PROTOBUF_C_OFFSETOF(Stream, column),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Stream, has_length),
    PROTOBUF_C_OFFSETOF(Stream, length),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stream__field_indices_by_name[] = {
  1,   /* field[1] = column */
  0,   /* field[0] = kind */
  2,   /* field[2] = length */
};
static const ProtobufCIntRange stream__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor stream__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Stream",
  "Stream",
  "Stream",
  "",
  sizeof(Stream),
  3,
  stream__field_descriptors,
  stream__field_indices_by_name,
  1,  stream__number_ranges,
  (ProtobufCMessageInit) stream__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue column_encoding__kind__enum_values_by_number[2] =
{
  { "DIRECT", "COLUMN_ENCODING__KIND__DIRECT", 0 },
  { "DICTIONARY", "COLUMN_ENCODING__KIND__DICTIONARY", 1 },
};
static const ProtobufCIntRange column_encoding__kind__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex column_encoding__kind__enum_values_by_name[2] =
{
  { "DICTIONARY", 1 },
  { "DIRECT", 0 },
};
const ProtobufCEnumDescriptor column_encoding__kind__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "ColumnEncoding.Kind",
  "Kind",
  "ColumnEncoding__Kind",
  "",
  2,
  column_encoding__kind__enum_values_by_number,
  2,
  column_encoding__kind__enum_values_by_name,
  1,
  column_encoding__kind__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor column_encoding__field_descriptors[2] =
{
  {
    "kind",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ColumnEncoding, kind),
    &column_encoding__kind__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dictionarySize",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(ColumnEncoding, has_dictionarysize),
    PROTOBUF_C_OFFSETOF(ColumnEncoding, dictionarysize),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned column_encoding__field_indices_by_name[] = {
  1,   /* field[1] = dictionarySize */
  0,   /* field[0] = kind */
};
static const ProtobufCIntRange column_encoding__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor column_encoding__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ColumnEncoding",
  "ColumnEncoding",
  "ColumnEncoding",
  "",
  sizeof(ColumnEncoding),
  2,
  column_encoding__field_descriptors,
  column_encoding__field_indices_by_name,
  1,  column_encoding__number_ranges,
  (ProtobufCMessageInit) column_encoding__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stripe_footer__field_descriptors[2] =
{
  {
    "streams",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(StripeFooter, n_streams),
    PROTOBUF_C_OFFSETOF(StripeFooter, streams),
    &stream__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "columns",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(StripeFooter, n_columns),
    PROTOBUF_C_OFFSETOF(StripeFooter, columns),
    &column_encoding__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stripe_footer__field_indices_by_name[] = {
  1,   /* field[1] = columns */
  0,   /* field[0] = streams */
};
static const ProtobufCIntRange stripe_footer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor stripe_footer__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "StripeFooter",
  "StripeFooter",
  "StripeFooter",
  "",
  sizeof(StripeFooter),
  2,
  stripe_footer__field_descriptors,
  stripe_footer__field_indices_by_name,
  1,  stripe_footer__number_ranges,
  (ProtobufCMessageInit) stripe_footer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue type__kind__enum_values_by_number[15] =
{
  { "BOOLEAN", "TYPE__KIND__BOOLEAN", 0 },
  { "BYTE", "TYPE__KIND__BYTE", 1 },
  { "SHORT", "TYPE__KIND__SHORT", 2 },
  { "INT", "TYPE__KIND__INT", 3 },
  { "LONG", "TYPE__KIND__LONG", 4 },
  { "FLOAT", "TYPE__KIND__FLOAT", 5 },
  { "DOUBLE", "TYPE__KIND__DOUBLE", 6 },
  { "STRING", "TYPE__KIND__STRING", 7 },
  { "BINARY", "TYPE__KIND__BINARY", 8 },
  { "TIMESTAMP", "TYPE__KIND__TIMESTAMP", 9 },
  { "LIST", "TYPE__KIND__LIST", 10 },
  { "MAP", "TYPE__KIND__MAP", 11 },
  { "STRUCT", "TYPE__KIND__STRUCT", 12 },
  { "UNION", "TYPE__KIND__UNION", 13 },
  { "DECIMAL", "TYPE__KIND__DECIMAL", 14 },
};
static const ProtobufCIntRange type__kind__value_ranges[] = {
{0, 0},{0, 15}
};
const ProtobufCEnumValueIndex type__kind__enum_values_by_name[15] =
{
  { "BINARY", 8 },
  { "BOOLEAN", 0 },
  { "BYTE", 1 },
  { "DECIMAL", 14 },
  { "DOUBLE", 6 },
  { "FLOAT", 5 },
  { "INT", 3 },
  { "LIST", 10 },
  { "LONG", 4 },
  { "MAP", 11 },
  { "SHORT", 2 },
  { "STRING", 7 },
  { "STRUCT", 12 },
  { "TIMESTAMP", 9 },
  { "UNION", 13 },
};
const ProtobufCEnumDescriptor type__kind__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "Type.Kind",
  "Kind",
  "Type__Kind",
  "",
  15,
  type__kind__enum_values_by_number,
  15,
  type__kind__enum_values_by_name,
  1,
  type__kind__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor type__field_descriptors[3] =
{
  {
    "kind",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Type, kind),
    &type__kind__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subtypes",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Type, n_subtypes),
    PROTOBUF_C_OFFSETOF(Type, subtypes),
    NULL,
    NULL,
    1,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fieldNames",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(Type, n_fieldnames),
    PROTOBUF_C_OFFSETOF(Type, fieldnames),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned type__field_indices_by_name[] = {
  2,   /* field[2] = fieldNames */
  0,   /* field[0] = kind */
  1,   /* field[1] = subtypes */
};
static const ProtobufCIntRange type__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor type__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Type",
  "Type",
  "Type",
  "",
  sizeof(Type),
  3,
  type__field_descriptors,
  type__field_indices_by_name,
  1,  type__number_ranges,
  (ProtobufCMessageInit) type__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor stripe_information__field_descriptors[5] =
{
  {
    "offset",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(StripeInformation, has_offset),
    PROTOBUF_C_OFFSETOF(StripeInformation, offset),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indexLength",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(StripeInformation, has_indexlength),
    PROTOBUF_C_OFFSETOF(StripeInformation, indexlength),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dataLength",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(StripeInformation, has_datalength),
    PROTOBUF_C_OFFSETOF(StripeInformation, datalength),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "footerLength",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(StripeInformation, has_footerlength),
    PROTOBUF_C_OFFSETOF(StripeInformation, footerlength),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "numberOfRows",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(StripeInformation, has_numberofrows),
    PROTOBUF_C_OFFSETOF(StripeInformation, numberofrows),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned stripe_information__field_indices_by_name[] = {
  2,   /* field[2] = dataLength */
  3,   /* field[3] = footerLength */
  1,   /* field[1] = indexLength */
  4,   /* field[4] = numberOfRows */
  0,   /* field[0] = offset */
};
static const ProtobufCIntRange stripe_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor stripe_information__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "StripeInformation",
  "StripeInformation",
  "StripeInformation",
  "",
  sizeof(StripeInformation),
  5,
  stripe_information__field_descriptors,
  stripe_information__field_indices_by_name,
  1,  stripe_information__number_ranges,
  (ProtobufCMessageInit) stripe_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor user_metadata_item__field_descriptors[2] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserMetadataItem, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserMetadataItem, value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned user_metadata_item__field_indices_by_name[] = {
  0,   /* field[0] = name */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange user_metadata_item__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor user_metadata_item__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "UserMetadataItem",
  "UserMetadataItem",
  "UserMetadataItem",
  "",
  sizeof(UserMetadataItem),
  2,
  user_metadata_item__field_descriptors,
  user_metadata_item__field_indices_by_name,
  1,  user_metadata_item__number_ranges,
  (ProtobufCMessageInit) user_metadata_item__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor footer__field_descriptors[8] =
{
  {
    "headerLength",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Footer, has_headerlength),
    PROTOBUF_C_OFFSETOF(Footer, headerlength),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contentLength",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Footer, has_contentlength),
    PROTOBUF_C_OFFSETOF(Footer, contentlength),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stripes",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Footer, n_stripes),
    PROTOBUF_C_OFFSETOF(Footer, stripes),
    &stripe_information__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "types",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Footer, n_types),
    PROTOBUF_C_OFFSETOF(Footer, types),
    &type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metadata",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Footer, n_metadata),
    PROTOBUF_C_OFFSETOF(Footer, metadata),
    &user_metadata_item__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "numberOfRows",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(Footer, has_numberofrows),
    PROTOBUF_C_OFFSETOF(Footer, numberofrows),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "statistics",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Footer, n_statistics),
    PROTOBUF_C_OFFSETOF(Footer, statistics),
    &column_statistics__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rowIndexStride",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(Footer, has_rowindexstride),
    PROTOBUF_C_OFFSETOF(Footer, rowindexstride),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned footer__field_indices_by_name[] = {
  1,   /* field[1] = contentLength */
  0,   /* field[0] = headerLength */
  4,   /* field[4] = metadata */
  5,   /* field[5] = numberOfRows */
  7,   /* field[7] = rowIndexStride */
  6,   /* field[6] = statistics */
  2,   /* field[2] = stripes */
  3,   /* field[3] = types */
};
static const ProtobufCIntRange footer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor footer__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "Footer",
  "Footer",
  "Footer",
  "",
  sizeof(Footer),
  8,
  footer__field_descriptors,
  footer__field_indices_by_name,
  1,  footer__number_ranges,
  (ProtobufCMessageInit) footer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor post_script__field_descriptors[5] =
{
  {
    "footerLength",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(PostScript, has_footerlength),
    PROTOBUF_C_OFFSETOF(PostScript, footerlength),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "compression",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(PostScript, has_compression),
    PROTOBUF_C_OFFSETOF(PostScript, compression),
    &compression_kind__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "compressionBlockSize",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(PostScript, has_compressionblocksize),
    PROTOBUF_C_OFFSETOF(PostScript, compressionblocksize),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(PostScript, n_version),
    PROTOBUF_C_OFFSETOF(PostScript, version),
    NULL,
    NULL,
    1,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "magic",
    8000,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(PostScript, magic),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned post_script__field_indices_by_name[] = {
  1,   /* field[1] = compression */
  2,   /* field[2] = compressionBlockSize */
  0,   /* field[0] = footerLength */
  4,   /* field[4] = magic */
  3,   /* field[3] = version */
};
static const ProtobufCIntRange post_script__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 8000, 4 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor post_script__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "PostScript",
  "PostScript",
  "PostScript",
  "",
  sizeof(PostScript),
  5,
  post_script__field_descriptors,
  post_script__field_indices_by_name,
  2,  post_script__number_ranges,
  (ProtobufCMessageInit) post_script__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue compression_kind__enum_values_by_number[4] =
{
  { "NONE", "COMPRESSION_KIND__NONE", 0 },
  { "ZLIB", "COMPRESSION_KIND__ZLIB", 1 },
  { "SNAPPY", "COMPRESSION_KIND__SNAPPY", 2 },
  { "LZO", "COMPRESSION_KIND__LZO", 3 },
};
static const ProtobufCIntRange compression_kind__value_ranges[] = {
{0, 0},{0, 4}
};
const ProtobufCEnumValueIndex compression_kind__enum_values_by_name[4] =
{
  { "LZO", 3 },
  { "NONE", 0 },
  { "SNAPPY", 2 },
  { "ZLIB", 1 },
};
const ProtobufCEnumDescriptor compression_kind__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "CompressionKind",
  "CompressionKind",
  "CompressionKind",
  "",
  4,
  compression_kind__enum_values_by_number,
  4,
  compression_kind__enum_values_by_name,
  1,
  compression_kind__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
